[package]
name = "congkit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
bimap = "0.6.3"
bitcode = "0.6.3"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
